#!/usr/bin/env bash
# Changes port in Nginx
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo nginx -t  # Check configuration syntax
sudo service nginx restart
sleep 2  # Add a delay before verifying the result
sudo nginx -t  # Check configuration syntax again
