#!/usr/bin/env bash

# Update Nginx configuration to use port 80
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default

# Restart Nginx and check its status
#service nginx restart

# Check if Nginx is running
#status=$(service nginx status)
#if [[ $status == "not running" ]]; then
#  echo " * nginx is not running"
#  exit 1
#fi

# Check if Nginx returns a web page with HTTP 200
response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost)
if [[ $response -eq 200 ]]; then
  echo "1"
else
  echo "0"
fi
